Nautilus Featured
subquery/ethereum-subql-starter pull request #58
Opened 2023-12-06 18:14 UTC by bgodlin

2023-12-06 21:19 UTC, deverka approved these changes

2023-12-10 23:28 UTC, deverka commented
@jamesbayly

2023-12-11 04:23 UTC, jamesbayly requested changes
Theres a few issues, these same things keep coming up

2023-12-11 04:23 UTC, jamesbayly commented on Nautilus/nautilus-starter/project.ts
> +    "This project can be use as a starting point for developing your new Ethereum SubQuery project",
```suggestion
    "This project can be use as a starting point for developing your new Nautilus SubQuery project",
```

2023-12-11 04:23 UTC, jamesbayly commented on Nautilus/nautilus-starter/project.ts
> +     * When developing your project we suggest getting a private API key
This has been updated on the main branch, please use the new formats

2023-12-11 04:23 UTC, jamesbayly commented on Nautilus/nautilus-starter/project.ts
> +      startBlock: 23976397,
Why was this chosen? Add it in as a comment

2023-12-11 04:23 UTC, jamesbayly commented on Nautilus/nautilus-starter/README.md
> +**This SubQuery project indexes all transfers and approval events for [Ether](https://nautscan.com/mainnet/search/0xB2723928400AE5778f6A3C69D7Ca9e90FC430180) (`0xBDa330Ea8F3005C421C8088e638fBB64fA71b
Wrapped ether?

2023-12-11 04:23 UTC, jamesbayly commented on Nautilus/nautilus-starter/docker-compose.yml
> +      - --batch-size=1
Can we leave this is a default of 30
```suggestion
      - --batch-size=30
```

2024-01-29 02:43 UTC, jamesbayly commented on Nautilus/nautilus-starter/project.ts
> +  name: "nautilus-subql-starter",
```suggestion
  name: "nautilus-starter",
```

2024-01-29 02:43 UTC, jamesbayly commented on Nautilus/nautilus-starter/package.json
> +  "name": "nautilus-subql-starter",
```suggestion
  "name": "nautilus-starter",
```

2024-01-29 02:44 UTC, jamesbayly commented on Nautilus/nautilus-starter/LICENSE
> +Copyright 2020-2021 SubQuery Pte Ltd authors & contributors
```suggestion
Copyright 2020-2024 SubQuery Pte Ltd authors & contributors
```

2024-01-29 02:44 UTC, jamesbayly approved these changes

2024-01-29 02:44 UTC, merged